/**
 * Deterministic shuffling, seeded by a content id.
 *
 * The order is generated by code, never hand-authored — that is the whole
 * point: an author cannot accidentally leave the correct option sitting in a
 * predictable slot. Because the seed is the id, the same quiz always renders
 * the same order (stable across visits and devices), which is what lets a
 * stored answer — held as an ORIGINAL index, never a display index — map back
 * correctly forever.
 *
 * Used for both option order within a question and question order within a
 * practice set, so the two can never drift apart.
 */

/** djb2 string hash -> mulberry32 PRNG -> Fisher-Yates. */
export function shuffledOrder(seedText: string, length: number): number[] {
  let seed = 5381;
  for (let i = 0; i < seedText.length; i++) seed = (seed * 33) ^ seedText.charCodeAt(i);
  const rand = () => {
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const order = Array.from({ length }, (_, i) => i);
  for (let i = length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [order[i], order[j]] = [order[j]!, order[i]!];
  }
  return order;
}
